name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Setup Node.js environment
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn' # use yarn for caching

      # Install dependencies
      - name: Install dependencies
        run: yarn install

      # If you are using Cypress, you can still install it
      # - name: Install Cypress
      #   run: yarn add cypress

      # Validate
      - name: Validate
        run: yarn lint && yarn test:ci && yarn test:e2e:ci
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      # Upload coverage
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
